Convert tabs to spaces

diff --git a/atlassian_rotate_tomcat_logs b/atlassian_rotate_tomcat_logs
--- a/atlassian_rotate_tomcat_logs
+++ b/atlassian_rotate_tomcat_logs
@@ -13,15 +13,15 @@
 
 # Must be root to run this script
 if [ "`/usr/bin/id -urn`" != "root" ] ; then
-        echo -e "\nYou must be root to execute this script \n"
-        exit 1
+  echo -e "\nYou must be root to execute this script \n"
+  exit 1
 fi
 
 USAGE() {
-        echo -e "\nUsage: `basename $0` [ -c | -j | -w ] "
-        echo -e "-c --> Rotate Confluence Tomcat logs"
-        echo -e "-j --> Rotate JIRA Tomcat logs"
-        echo -e "-w --> Rotate Crowd Tomcat logs"
+  echo -e "\nUsage: `basename $0` [ -c | -j | -w ] "
+  echo -e "-c --> Rotate Confluence Tomcat logs"
+  echo -e "-j --> Rotate JIRA Tomcat logs"
+  echo -e "-w --> Rotate Crowd Tomcat logs"
 }
 
 INSTALL_DIR="/usr/local/atlassian"
@@ -29,41 +29,40 @@ SAVETIME=180
 APP="null"
 
 while getopts ":cjw" OPT ; do
-        case $OPT in
-                c)
-                        APP="confluence"
-			TOMCAT_LOG_DIR="$INSTALL_DIR/confluence/logs"
-                        ;;
-                j)
-                        APP="jira"
-			TOMCAT_LOG_DIR="$INSTALL_DIR/jira/logs"
-                        ;;
-                w)
-                        APP="crowd"
-			TOMCAT_LOG_DIR="$INSTALL_DIR/crowd/apache-tomcat/logs"
-                        ;;
-                \?)
-                        echo -e "\nInvalid option: -$OPTARG" >&2
-                        USAGE
-                        exit 1
-                        ;;
-                :)
-                        echo -e "\nOption -$OPTARG requires an argument" >&2
-                        USAGE
-                        exit 1
-                        ;;
-        esac
+  case $OPT in
+    c)
+      APP="confluence"
+      TOMCAT_LOG_DIR="$INSTALL_DIR/confluence/logs"
+      ;;
+    j)
+      APP="jira"
+      TOMCAT_LOG_DIR="$INSTALL_DIR/jira/logs"
+      ;;
+    w)
+      APP="crowd"
+      TOMCAT_LOG_DIR="$INSTALL_DIR/crowd/apache-tomcat/logs"
+      ;;
+    \?)
+      echo -e "\nInvalid option: -$OPTARG" >&2
+      USAGE
+      exit 1
+      ;;
+    :)
+      echo -e "\nOption -$OPTARG requires an argument" >&2
+      USAGE
+      exit 1
+      ;;
+  esac
 done
 
 if [ "$APP" == "null" ] ; then
-        USAGE
-        exit 1
+  USAGE
+  exit 1
 fi
 
 if [ ! -r $TOMCAT_LOG_DIR ] ; then
-	echo -e "\nTomcat log directory $TOMCAT_LOG_DIR could not be accessed.\n"
-	exit 1
+  echo -e "\nTomcat log directory $TOMCAT_LOG_DIR could not be accessed.\n"
+  exit 1
 fi
 
 find $TOMCAT_LOG_DIR -type f -name "*.????-??-??*" -mtime +$SAVETIME | xargs rm -vf
-
